services:
  main:
    build:
      context: .
      network: host
      target: development
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - .:/go/src/app
      - cache:/go/pkg
    tty: true

volumes:
  cache:
