/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.1.4 (4.1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the PatchedTopologyDummyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedTopologyDummyRequest{}

// PatchedTopologyDummyRequest struct for PatchedTopologyDummyRequest
type PatchedTopologyDummyRequest struct {
	Name                 NullableString `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedTopologyDummyRequest PatchedTopologyDummyRequest

// NewPatchedTopologyDummyRequest instantiates a new PatchedTopologyDummyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedTopologyDummyRequest() *PatchedTopologyDummyRequest {
	this := PatchedTopologyDummyRequest{}
	return &this
}

// NewPatchedTopologyDummyRequestWithDefaults instantiates a new PatchedTopologyDummyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedTopologyDummyRequestWithDefaults() *PatchedTopologyDummyRequest {
	this := PatchedTopologyDummyRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedTopologyDummyRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedTopologyDummyRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *PatchedTopologyDummyRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *PatchedTopologyDummyRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *PatchedTopologyDummyRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *PatchedTopologyDummyRequest) UnsetName() {
	o.Name.Unset()
}

func (o PatchedTopologyDummyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedTopologyDummyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedTopologyDummyRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedTopologyDummyRequest := _PatchedTopologyDummyRequest{}

	err = json.Unmarshal(data, &varPatchedTopologyDummyRequest)

	if err != nil {
		return err
	}

	*o = PatchedTopologyDummyRequest(varPatchedTopologyDummyRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedTopologyDummyRequest struct {
	value *PatchedTopologyDummyRequest
	isSet bool
}

func (v NullablePatchedTopologyDummyRequest) Get() *PatchedTopologyDummyRequest {
	return v.value
}

func (v *NullablePatchedTopologyDummyRequest) Set(val *PatchedTopologyDummyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedTopologyDummyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedTopologyDummyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedTopologyDummyRequest(val *PatchedTopologyDummyRequest) *NullablePatchedTopologyDummyRequest {
	return &NullablePatchedTopologyDummyRequest{value: val, isSet: true}
}

func (v NullablePatchedTopologyDummyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedTopologyDummyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
