/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.1.4 (4.1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the RoleImageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleImageRequest{}

// RoleImageRequest struct for RoleImageRequest
type RoleImageRequest struct {
	Image                string `json:"image"`
	AdditionalProperties map[string]interface{}
}

type _RoleImageRequest RoleImageRequest

// NewRoleImageRequest instantiates a new RoleImageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleImageRequest(image string) *RoleImageRequest {
	this := RoleImageRequest{}
	this.Image = image
	return &this
}

// NewRoleImageRequestWithDefaults instantiates a new RoleImageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleImageRequestWithDefaults() *RoleImageRequest {
	this := RoleImageRequest{}
	return &this
}

// GetImage returns the Image field value
func (o *RoleImageRequest) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *RoleImageRequest) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *RoleImageRequest) SetImage(v string) {
	o.Image = v
}

func (o RoleImageRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleImageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["image"] = o.Image

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RoleImageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoleImageRequest := _RoleImageRequest{}

	err = json.Unmarshal(data, &varRoleImageRequest)

	if err != nil {
		return err
	}

	*o = RoleImageRequest(varRoleImageRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "image")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRoleImageRequest struct {
	value *RoleImageRequest
	isSet bool
}

func (v NullableRoleImageRequest) Get() *RoleImageRequest {
	return v.value
}

func (v *NullableRoleImageRequest) Set(val *RoleImageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleImageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleImageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleImageRequest(val *RoleImageRequest) *NullableRoleImageRequest {
	return &NullableRoleImageRequest{value: val, isSet: true}
}

func (v NullableRoleImageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleImageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
